"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import api from "@/lib/api";
import { Loading, PageTitle, Status, useGet } from "@/components/erp/shared";
import { fileUrl } from "@/lib/utils";

const segments =["Food & Beverage","Pharmaceutical","Cosmetics","Manufacturing (Non-F&B)","Warehouse / Logistics","Hotel","Mall","Restaurant / Café","Office / Office Building","Hospital / Healthcare","School / Education","Retail Store","Residential - House","Residential - Apartment","Residential - Ruko","Apartment Building (Management)","Housing Cluster / Developer","Oil&Gas","Power Generation","Contractor/Construction"];
const options: Record<string, string[]> = { status: ["Renewal", "Kontrak", "Non-Kontrak"], segment: segments, segmentType: ["B2B", "B2C"], vendorName: ["Pestigo", "Istapest", "Pascal", "PCO", "SPC", "Riztra"], treatment: ["PC", "RC", "PCRC", "Termite", "Other"], agreementType: ["Simple", "Full"] };
const numericFields = new Set(["agreementDurationMonths", "invoiceAcceptanceLimitDays"]);
const groups = [
  ["Data Customer", [["Nama Customer", "name"], ["Nama Perusahaan", "company"], ["Alamat Customer (Treatment)", "treatmentAddress"], ["DPP Vendor", "dppVendor"], ["DPP FI", "dppFi"]]],
  ["Status & Layanan", [["Status Customer", "status"], ["Customer Segment", "segment"], ["Segment Type", "segmentType"], ["Nama Vendor", "vendorName"], ["Treatment", "treatment"], ["Jenis Agreement", "agreementType"], ["Durasi Agreement (Bulan)", "agreementDurationMonths"]]],
  ["PIC Service & Schedule", [["Nama PIC Service", "picServiceName"], ["Kontak PIC Service", "picServicePhone"], ["Email PIC Service", "picServiceEmail"], ["PIC Schedule", "picScheduleName"], ["Kontak PIC Schedule", "picSchedulePhone"]]],
  ["Pajak & Quality", [["Nomor KTP Penanggung Jawab / Pemilik", "responsibleOwnerKtp"], ["Nama NPWP", "npwpName"], ["Nomor NPWP", "npwpNumber"], ["Alamat NPWP", "npwpAddress"], ["Frekuensi Monthly Report", "monthlyReportFrequency"], ["Lead Source", "leadSource"], ["Nama QC", "qcName"], ["Nama QA", "qaName"]]],
  ["Agreement & Invoice", [["Nama PIC Agreement", "agreementPicName"], ["Jabatan PIC Agreement", "agreementPicTitle"], ["PIC Invoice", "invoicePicName"], ["Kontak PIC Invoice", "invoicePicPhone"], ["Email PIC Invoice", "invoicePicEmail"], ["Alamat PIC Invoice", "invoicePicAddress"], ["Batas Penerimaan Invoice Customer (Hari)", "invoiceAcceptanceLimitDays"]]],
] as const;
const pretty=(value:any)=>value ? (typeof value === "string" && value.includes("T") ? new Date(value).toLocaleDateString("id-ID") : String(value).replaceAll("_", " ")) : "-";

function EditableField({ customerId, label, field, value, reload }: { customerId: string; label: string; field: string; value: any; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(value ?? ""); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { await api.patch(`/erp/customers/${customerId}`, { [field]: draft }); await reload(); setEditing(false); } finally { setSaving(false); } };
  const inputType = numericFields.has(field) ? "number" : "text";
  return <div><dt className="text-xs font-bold tracking-wide text-ts">{label}</dt>{editing ? <div className="mt-2 flex gap-2">{options[field] ? <select value={draft} onChange={event=>setDraft(event.target.value)}>{options[field].map(option=><option key={option}>{option}</option>)}</select> : <input type={inputType} value={draft} onChange={event=>setDraft(event.target.value)} />}<button className="btn btn-primary !min-h-0 px-3 py-1 text-xs" disabled={saving} onClick={save}>Simpan</button><button className="btn !min-h-0 px-3 py-1 text-xs" onClick={()=>{setDraft(value??"");setEditing(false);}}>Batal</button></div> : <dd className="mt-1 flex items-start gap-2 text-sm font-medium"><span>{pretty(value)}</span><button className="text-xs font-semibold text-accent hover:underline" onClick={()=>setEditing(true)}>Edit</button></dd>}</div>;
}

function FilesTab({ customer, reload }: { customer: any; reload: () => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [name, setName] = useState(""); const [category, setCategory] = useState("OTHER"); const [description, setDescription] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!file) return setError("Pilih file terlebih dahulu."); setSaving(true); setError(""); try { const form = new FormData(); form.append("file", file); form.append("name", name || file.name); form.append("category", category); form.append("description", description); await api.post(`/erp/customers/${customer.id}/files`, form); setFile(null); setName(""); setDescription(""); await reload(); } catch (requestError:any) { setError(requestError.response?.data?.error || "Upload file gagal."); } finally { setSaving(false); } }
  return <div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={upload} className="card p-6"><h2 className="text-lg font-bold">Upload File Customer</h2><p className="mt-2 text-sm text-ts">PDF, gambar, Word, atau Excel. Maksimal 15 MB.</p><div className="mt-5 space-y-4"><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx" onChange={event=>setFile(event.target.files?.[0] || null)} /><input placeholder="Nama dokumen (opsional)" value={name} onChange={event=>setName(event.target.value)} /><select value={category} onChange={event=>setCategory(event.target.value)}><option value="CONTRACT">Agreement / Kontrak</option><option value="TREATMENT_REPORT">Laporan Treatment</option><option value="NPWP">NPWP</option><option value="INVOICE">Invoice</option><option value="OTHER">Lainnya</option></select><textarea rows={3} placeholder="Keterangan file (opsional)" value={description} onChange={event=>setDescription(event.target.value)} />{error&&<p className="text-sm text-red-700">{error}</p>}<button className="btn btn-primary w-full" disabled={saving}>{saving ? "Mengunggah..." : "Upload File"}</button></div></form><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-bdr p-6"><h2 className="text-lg font-bold">File Customer</h2><span className="text-sm text-ts">{customer.files?.length || 0} file</span></div>{customer.files?.length ? <table><thead><tr><th>Nama File</th><th>Kategori</th><th>Ukuran</th><th>Tanggal</th><th></th></tr></thead><tbody>{customer.files.map((item:any)=><tr key={item.id}><td><b>{item.name}</b>{item.description&&<p className="mt-1 text-xs text-ts">{item.description}</p>}</td><td><span className="badge badge-draft">{item.category.replaceAll("_", " ")}</span></td><td>{Math.max(1, Math.ceil(item.size / 1024))} KB</td><td>{new Date(item.createdAt).toLocaleDateString("id-ID")}</td><td><a className="font-semibold text-accent hover:underline" href={fileUrl(item.filePath)} target="_blank">Buka</a></td></tr>)}</tbody></table> : <div className="p-10 text-center text-sm text-ts">Belum ada file untuk customer ini.</div>}</section></div>;
}

export default function CustomerDetail(){const {id}=useParams<{id:string}>();const {data,loading,error,reload}=useGet<any>(`/erp/customers/${id}`);const [tab,setTab]=useState<"data"|"files">("data");if(loading)return <div className="p-9"><Loading/></div>;if(!data)return <div className="p-9"><Link className="text-accent underline" href="/customers">← Kembali ke Customer</Link><p className="mt-5 text-red-700">{error || "Customer tidak ditemukan."}</p></div>;return <div className="p-9"><PageTitle title={data.name} subtitle={`${data.company||"Tanpa perusahaan"} · ${data.code}`} actions={<Link className="btn" href="/customers">← Kembali ke Customer</Link>}/><div className="mt-7 flex flex-wrap gap-3"><Status value={data.status}/><span className="badge badge-draft">{data.segment||"Belum dipilih"}</span></div><div className="mt-7 flex gap-1 border-b border-bdr"><button onClick={()=>setTab("data")} className={`px-5 py-3 text-sm font-semibold ${tab==="data" ? "border-b-2 border-accent text-accent" : "text-ts"}`}>Data Customer</button><button onClick={()=>setTab("files")} className={`px-5 py-3 text-sm font-semibold ${tab==="files" ? "border-b-2 border-accent text-accent" : "text-ts"}`}>Upload File <span className="ml-1 rounded-full bg-surface px-2 py-0.5 text-xs">{data.files?.length||0}</span></button></div>{tab==="data" ? <><p className="mt-5 text-sm text-ts">Klik <b>Edit</b> pada field yang ingin diperbarui, lalu simpan tanpa meninggalkan halaman detail.</p><div className="mt-6 grid gap-6 xl:grid-cols-2">{groups.map(([title,fields])=><section className="card p-6" key={title}><h2 className="border-b border-bdr pb-4 text-lg font-bold">{title}</h2><dl className="mt-4 grid gap-x-6 gap-y-5 md:grid-cols-2">{fields.map(([label,key])=><EditableField key={key} customerId={data.id} label={label} field={key} value={data[key]} reload={reload}/>)}</dl></section>)}</div><section className="card mt-6 overflow-hidden"><h2 className="border-b border-bdr p-6 text-lg font-bold">Riwayat Customer</h2><div className="grid gap-4 p-6 md:grid-cols-3"><div><p className="text-xs font-bold text-ts">INQUIRY</p><p className="mt-2 text-3xl font-bold">{data.inquiries?.length||0}</p></div><div><p className="text-xs font-bold text-ts">QUOTATION</p><p className="mt-2 text-3xl font-bold">{data.quotations?.length||0}</p></div><div><p className="text-xs font-bold text-ts">SURVEY</p><p className="mt-2 text-3xl font-bold">{data.surveys?.length||0}</p></div></div></section></> : <FilesTab customer={data} reload={reload}/>}</div>}
