"use client";
import { Loading, PageTitle, Status, useGet } from "./shared";

const formatDate=(v:string)=>new Date(v).toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});

function Summary({label,value}:{label:string;value:number}){return <div className="card p-6"><p className="text-xs font-bold tracking-wider text-ts">{label}</p><p className="mt-5 text-4xl font-bold">{value}</p></div>}

export function Quotations(){const {data,loading}=useGet<any>("/erp/quotations");return <div className="p-9"><PageTitle title="Daftar Penawaran" subtitle="Kelola dan pantau seluruh status penawaran harga pelanggan." actions={<button className="btn btn-primary">+ Buat Quotation Baru</button>}/><section className="mt-8 grid gap-5 md:grid-cols-4"><Summary label="TOTAL" value={data?.total||0}/><Summary label="APPROVED" value={data?.data?.filter((x:any)=>x.status==="APPROVED").length||0}/><Summary label="PENDING" value={data?.data?.filter((x:any)=>x.status==="SENT").length||0}/><Summary label="REJECTED" value={data?.data?.filter((x:any)=>x.status==="REJECTED").length||0}/></section><div className="card mt-6 overflow-hidden">{loading?<Loading/>:<table><thead><tr><th>ID Quotation</th><th>Nama Pelanggan</th><th>Nilai Penawaran</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{data?.data?.map((x:any)=><tr key={x.id}><td className="font-semibold text-accent">#{x.number}</td><td>{x.customer.name}</td><td className="font-semibold">Rp {Number(x.amount).toLocaleString("id-ID")}</td><td><Status value={x.status}/></td><td>{formatDate(x.createdAt)}</td></tr>)}</tbody></table>}</div></div>}

export function Renewals(){const {data,loading}=useGet<any>("/erp/renewals");return <div className="p-9"><PageTitle title="Renewal Management" subtitle="Monitor dan kelola masa berlaku kontrak pelanggan."/><div className="mt-7 flex gap-8 border-b border-bdr pb-4 font-medium"><span className="text-accent">Agreements</span><span>Outstanding (OS)</span><span>Notifications</span></div><section className="mt-7 grid gap-5 md:grid-cols-3"><Summary label="CRITICAL RENEWALS" value={data?.data?.filter((x:any)=>x.progress<30).length||0}/><Summary label="AWAITING ACTION" value={data?.data?.filter((x:any)=>x.status==="UPCOMING").length||0}/><Summary label="COMPLETED MTD" value={data?.data?.filter((x:any)=>x.status==="RENEWED").length||0}/></section><div className="card mt-6 overflow-hidden">{loading?<Loading/>:<table><thead><tr><th>Contract ID</th><th>Customer Name</th><th>Expiry Date</th><th>Status / Progress</th><th>Action</th></tr></thead><tbody>{data?.data?.map((x:any)=><tr key={x.id}><td className="font-semibold text-accent">#{x.number}</td><td>{x.customer.name}</td><td>{formatDate(x.expiryDate)}</td><td><div className="h-2 w-36 rounded bg-surface"><div className="h-2 rounded bg-accent" style={{width:`${x.progress}%`}}/></div><p className="mt-2 text-xs">{x.progress}% complete</p></td><td><Status value={x.status}/></td></tr>)}</tbody></table>}</div></div>}
