"use client";
import { ReactNode, useEffect, useState } from "react";
import api from "@/lib/api";
export function PageTitle({ title, subtitle, actions }: { title: string; subtitle: string; actions?: ReactNode }) { return <div className="flex flex-col gap-5 border-b border-[#d9ddeb] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.14em] text-accent">Dashboard <span className="mx-1 text-ts">›</span> {title}</p><h1 className="text-3xl font-extrabold tracking-tight text-tp sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ts sm:text-base">{subtitle}</p></div>{actions && <div className="flex flex-wrap gap-3">{actions}</div>}</div>; }
export function Metric({ label, value, hint, tone = "normal" }: { label: string; value: string | number; hint?: string; tone?: "normal" | "good" | "warn" | "danger" }) { const color={normal:"text-[#181c22]",good:"text-[#16713b]",warn:"text-[#9a4f00]",danger:"text-[#ba1a1a]"}[tone]; return <div className="card min-h-[145px] p-5 sm:p-6"><p className="text-[11px] font-bold tracking-[.1em] text-ts">{label}</p><p className={`mt-4 text-4xl font-extrabold ${color}`}>{value}</p>{hint && <p className="mt-3 text-sm text-ts">{hint}</p>}</div>; }
export function Status({ value }: { value: string }) { return <span className={`badge badge-${value.toLowerCase().replaceAll("_", "-")}`}>{value.replaceAll("_", " ")}</span>; }
export function Loading() { return <div className="p-10 text-center text-ts">Memuat data...</div>; }
export function useGet<T>(url: string) { const [data,setData]=useState<T | null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const load=async()=>{setLoading(true);try{setData((await api.get(url)).data);}catch(e:any){setError(e.response?.data?.error||"Data tidak dapat dimuat");}finally{setLoading(false);}}; useEffect(()=>{load();},[url]); return {data,loading,error,reload:load}; }
export function Modal({ open, title, children, onClose, tone = "default" }: {open:boolean;title:string;children:ReactNode;onClose:()=>void;tone?:"default"|"danger"}) { if(!open)return null; const danger=tone==="danger"; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><div className={`card max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl ${danger ? "border-2 border-red-200" : ""}`}><div className="mb-5 flex justify-between"><h2 className={`text-xl font-bold ${danger ? "text-[#ba1a1a]" : ""}`}>{title}</h2><button className="text-xl" onClick={onClose}>×</button></div>{children}</div></div>; }
